### ISSUE TITLE
Error message when running node index.js

### ISSUE THREAD

**Issue by kaylamillerdev** [casmith/sync-todoist-to-habitica#3]
![image](https://user-images.githubusercontent.com/52870645/80990076-d2266880-8e03-11ea-98a2-af3c8f595838.png)

Me being a JS developer myself, i am pretty used to seeing error messages and can usually decipher them. There is a 404 error that pops up immediately following the line "Todoist: Daily Goal" task not configured. I'm assuming this has to do with the daily productivity goal in Todoist (which i do have set up but when i ran the command i had already completed the goal for the day). 

Also, some of my tasks have a string of numbers in brackets after the text and i'm not really sure what that's about.

**Comment by casmith** [comment]
The 404, I'm not sure about. Can you provide any other information to help me diagnose? Does the sync seem to be working otherwise? 

As for the bracketed numbers showing up in tasks, I assume this is when you have subtasks in todoist. There was no way to tag a subtask in habitica with a unique ID from todoist aside from shoving the ID inside the subtask description, so that's what I did. In the future I might better this by using some local database for storing mapping from todoist -> habitica tasks to make it cleaner.

**Comment by Kayla-D-Miller** [comment]
There really ism't much to say about it other than that I was running "node index.js" (as defined in the docker file) when it happened. I ran the program again but got a different set of errors this time:
![image](https://user-images.githubusercontent.com/52870645/82156740-0578e680-984b-11ea-9765-51b708c6ec06.png)

**Comment by casmith** [comment]
Your theory is possible. I made a bunch of changes since you had this error, please try again and open another issues if you still have problems.
